module.exports = {
	NETWORK_ERROR: "NETWORK_ERROR",
	RESPONSE_ERROR: "RESPONSE_ERROR",
	NOT_FOUND: "NOT_FOUND",
	UNAUTHENTICATED: "UNAUTHENTICATED",
	INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
	UNKNOWN_ERROR: "UNKNOWN_ERROR"
};
